apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Explicitly include each manifest (no recursion)
resources:
  - adservice.yaml
  - cartservice.yaml
  - checkoutservice.yaml
  - currencyservice.yaml
  - emailservice.yaml
  - frontend.yaml
  - loadgenerator.yaml
  - paymentservice.yaml
  - productcatalogservice.yaml
  - recommendationservice.yaml
  - shippingservice.yaml

# Rewrite simple image names like "adservice" -> Docker Hub images
images:
  - name: adservice
    newName: anvesh35/microservices-demo-adservice
    newTag: latest

  - name: cartservice
    newName: anvesh35/microservices-demo-cartservice
    newTag: latest

  - name: checkoutservice
    newName: anvesh35/microservices-demo-checkoutservice
    newTag: latest

  - name: currencyservice
    newName: anvesh35/microservices-demo-currencyservice
    newTag: latest

  - name: emailservice
    newName: anvesh35/microservices-demo-emailservice
    newTag: latest

  - name: frontend
    newName: anvesh35/microservices-demo-frontend
    newTag: latest

  - name: loadgenerator
    newName: anvesh35/microservices-demo-loadgenerator
    newTag: latest

  - name: paymentservice
    newName: anvesh35/microservices-demo-paymentservice
    newTag: latest

  - name: productcatalogservice
    newName: anvesh35/microservices-demo-productcatalogservice
    newTag: latest

  - name: recommendationservice
    newName: anvesh35/microservices-demo-recommendationservice
    newTag: latest

  - name: shippingservice
    newName: anvesh35/microservices-demo-shippingservice
    newTag: latest
