apiVersion: apps/v1
kind: Deployment
metadata:
  name: loadgenerator
  labels:
    app: loadgenerator
spec:
  # ❗ No test load on a laptop
  replicas: 0
  selector:
    matchLabels:
      app: loadgenerator
  template:
    metadata:
      labels:
        app: loadgenerator
    spec:
      containers:
        - name: main
          image: anvesh35/microservices-demo-loadgenerator:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: FRONTEND_ADDR
              value: "frontend:80"
          # tiny resources, just in case you ever scale it
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 100m
              memory: 128Mi
